name: Docker Build (Latest)
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Build
      run: docker build -f $GITHUB_WORKSPACE/docker/Dockerfile_latest $GITHUB_WORKSPACE/docker
